import { BlogPlaceholderImage } from '@/components/images';

export const BLOG_LISTING_CONST = [
  {
    id: 1,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: BlogPlaceholderImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Best Pujari in the town: You should probably',
    description:
      'Lorem ipsum dolor sit amet, consectetur fdshf adipiscing elit, sed do eiusmod tempor dghfhf incididunt ut labore etc',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 2,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: BlogPlaceholderImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Best Pujari in the town: You should probably do more',
    description:
      'Lorem ipsum dolor sit amet, consectetur fdshf adipiscing elit, sed do eiusmod tempor dghfhf incididunt ut labore etc',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 3,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: BlogPlaceholderImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Best Pujari in the town: You should probably do more',
    description:
      'Lorem ipsum dolor sit amet, consectetur fdshf adipiscing elit, sed do eiusmod tempor dghfhf incididunt ut labore etc',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 4,
    date: 'August 18, 2022',
    feature: ['Horoscope', 'Daily Prediction'],
    image: BlogPlaceholderImage,
    author: 'Rajesh Sharma',
    duration: '2 Min',
    views: '12456',
    title: 'Understanding Your Daily Horoscope: A Complete Guide',
    description:
      'Learn how to interpret your daily horoscope and make the most of astrological guidance in your everyday life.',
    link: '/blog/understanding-your-daily-horoscope-complete-guide',
  },
  {
    id: 5,
    date: 'August 15, 2022',
    feature: ['Vedic Astrology', 'Birth Chart'],
    image: BlogPlaceholderImage,
    author: 'Priya Joshi',
    duration: '3 Min',
    views: '9876',
    title: 'The Power of Birth Charts in Vedic Astrology',
    description:
      'Discover how your birth chart can reveal hidden aspects of your personality and life path according to Vedic traditions.',
    link: '/blog/power-of-birth-charts-vedic-astrology',
  },
  {
    id: 6,
    date: 'August 12, 2022',
    feature: ['Festivals', 'Religious Practices'],
    image: BlogPlaceholderImage,
    author: 'Amit Kumar',
    duration: '2 Min',
    views: '15678',
    title: 'Teej Festival: Significance and Celebrations',
    description:
      'Explore the cultural and spiritual importance of Teej festival and how it brings communities together.',
    link: '/blog/teej-festival-significance-celebrations',
  },
  {
    id: 7,
    date: 'August 10, 2022',
    feature: ['Mantras', 'Spiritual Healing'],
    image: BlogPlaceholderImage,
    author: 'Dr. Sunita Devi',
    duration: '4 Min',
    views: '11234',
    title: 'Healing Mantras for Mental Peace and Wellness',
    description:
      'Learn powerful mantras that can help you achieve mental peace and overall wellness in your daily life.',
    link: '/blog/healing-mantras-mental-peace-wellness',
  },
  {
    id: 8,
    date: 'August 8, 2022',
    feature: ['Gemstones', 'Astrology'],
    image: BlogPlaceholderImage,
    author: 'Vikram Singh',
    duration: '3 Min',
    views: '8765',
    title: 'Choosing the Right Gemstone Based on Your Zodiac',
    description:
      'Find out which gemstones are most beneficial for your zodiac sign and how they can enhance your life.',
    link: '/blog/choosing-right-gemstone-based-zodiac',
  },
  {
    id: 9,
    date: 'August 5, 2022',
    feature: ['Meditation', 'Spiritual Growth'],
    image: BlogPlaceholderImage,
    author: 'Meera Patel',
    duration: '2 Min',
    views: '13456',
    title: 'Meditation Techniques for Spiritual Awakening',
    description:
      'Simple yet effective meditation techniques that can help you on your spiritual journey and inner growth.',
    link: '/blog/meditation-techniques-spiritual-awakening',
  },
  {
    id: 10,
    date: 'August 3, 2022',
    feature: ['Numerology', 'Life Path'],
    image: BlogPlaceholderImage,
    author: 'Suresh Pandey',
    duration: '3 Min',
    views: '9876',
    title: 'Numerology: Understanding Your Life Path Number',
    description:
      'Discover how numerology can help you understand your life purpose and make better life decisions.',
    link: '/blog/numerology-understanding-life-path-number',
  },
  {
    id: 11,
    date: 'August 1, 2022',
    feature: ['Feng Shui', 'Home Energy'],
    image: BlogPlaceholderImage,
    author: 'Lisa Wang',
    duration: '4 Min',
    views: '14567',
    title: 'Feng Shui Tips for Positive Home Energy',
    description:
      'Learn how to arrange your living space using Feng Shui principles to attract positive energy and harmony.',
    link: '/blog/feng-shui-tips-positive-home-energy',
  },
  {
    id: 12,
    date: 'July 28, 2022',
    feature: ['Tarot Cards', 'Divination'],
    image: BlogPlaceholderImage,
    author: 'Sarah Johnson',
    duration: '3 Min',
    views: '12345',
    title: "Tarot Card Reading: A Beginner's Guide",
    description:
      'Everything you need to know to start your journey with tarot card reading and divination practices.',
    link: '/blog/tarot-card-reading-beginners-guide',
  },
];
