import {
  GaneshPujaBidhiImage,
  ShivaPujaBidhiImage,
  VishnuPujaBidhiImage,
} from '@/components/images/puja-bidhi';

export const PUJA_BIDHI_CONST = [
  {
    id: 1,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: ShivaPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Shiva Puja Bidhi',
    description:
      'Lord Shiva is revered as the Supreme Consciousness  the destroyer of negativity, the source of transformation,',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 2,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: VishnuPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Vishnu Puja Bidhi',
    description:
      'Lord Vishnu is worshipped as the protector and sustainer of life. Performing Vishnu pūjā brings harmony, prosperity.',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 3,
    date: 'August 20, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: GaneshPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Ganesh Puja Bidhi',
    description:
      'Lord Ganesha is always worshipped first before any other deity or new beginning. This pūjā invokes blessings for wisdom',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 4,
    date: 'August 18, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: ShivaPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Shiva Puja Bidhi',
    description:
      'Lord Shiva is revered as the Supreme Consciousness  the destroyer of negativity, the source of transformation,',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 5,
    date: 'August 18, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: VishnuPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Vishnu Puja Bidhi',
    description:
      'Lord Vishnu is worshipped as the protector and sustainer of life. Performing Vishnu pūjā brings harmony, prosperity.',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 6,
    date: 'August 18, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: GaneshPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Ganesh Puja Bidhi',
    description:
      'Lord Ganesha is always worshipped first before any other deity or new beginning. This pūjā invokes blessings for wisdom',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 7,
    date: 'August 15, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: ShivaPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Shiva Puja Bidhi',
    description:
      'Lord Shiva is revered as the Supreme Consciousness  the destroyer of negativity, the source of transformation,',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 8,
    date: 'August 15, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: VishnuPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Vishnu Puja Bidhi',
    description:
      'Lord Vishnu is worshipped as the protector and sustainer of life. Performing Vishnu pūjā brings harmony, prosperity.',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 9,
    date: 'August 15, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: GaneshPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Ganesh Puja Bidhi',
    description:
      'Lord Ganesha is always worshipped first before any other deity or new beginning. This pūjā invokes blessings for wisdom',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 10,
    date: 'August 12, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: ShivaPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Shiva Puja Bidhi',
    description:
      'Lord Shiva is revered as the Supreme Consciousness  the destroyer of negativity, the source of transformation,',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 11,
    date: 'August 12, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: VishnuPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Vishnu Puja Bidhi',
    description:
      'Lord Vishnu is worshipped as the protector and sustainer of life. Performing Vishnu pūjā brings harmony, prosperity.',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
  {
    id: 12,
    date: 'August 12, 2022',
    feature: ['Astrology', 'Puja Bidhi'],
    image: GaneshPujaBidhiImage,
    author: 'Seema Simkhada',
    duration: '1 Min',
    views: '8523',
    title: 'Ganesh Puja Bidhi',
    description:
      'Lord Ganesha is always worshipped first before any other deity or new beginning. This pūjā invokes blessings for wisdom',
    link: '/blogs/best-pujari-in-the-town-you-should-probably',
  },
];
