import type { Metadata } from 'next';
import { Tiro_Devanagari_Sanskrit, Sahitya, Mukta } from 'next/font/google';

import './globals.css';
import clsx from 'clsx';

const tiroDevanagari = Tiro_Devanagari_Sanskrit({
  variable: '--font-tiro-devanagari',
  subsets: ['latin', 'devanagari'],
  weight: '400',
});

const sahitya = Sahitya({
  variable: '--font-sahitya',
  subsets: ['latin', 'devanagari'],
  weight: ['400', '700'],
});

const mukta = Mukta({
  variable: '--font-mukta',
  subsets: ['latin', 'devanagari'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(tiroDevanagari.variable, sahitya.variable, mukta.variable, `antialiased`)}
      >
        {children}
      </body>
    </html>
  );
}
